{
 "title": "Failure Metrics",
 "time": { "from": "now/M", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "groupId", "label": "groupId", "query": "${VAR_GROUPID}" },
   { "name": "groupName", "label": "groupName", "query": "${VAR_GROUPNAME}" },
   { "name": "machineId", "query": "${VAR_MACHINEID}" },
   { "name": "parameterName", "query": "${VAR_PARAMETERNAME}" },
   { "name": "timeType", "query": "${VAR_TIMETYPE}" },
   { "name": "energyDeviceKind", "query": "${VAR_ENERGYDEVICEKIND}" },
   { "name": "usages", "query": "${VAR_USAGES}" },
   { "name": "alarmLevels", "query": "${VAR_ALARMLEVELS}" }
  ]
 },
 "panels": [
  {
   "title": "-",
   "type": "advantech-ifp-switch-panel",
   "gridPos": {
    "h": 2.4,
    "i18n": { "en-US": { "h": 2.4, "w": 24, "x": 0, "y": 0 } },
    "w": 24,
    "x": 0,
    "y": 0
   }
  },
  {
   "title": "MTBF",
   "type": "grouped-bar-chart-panel",
   "gridPos": {
    "h": 6.8,
    "i18n": { "en-US": { "h": 6.8, "w": 12, "x": 0, "y": 2.4 } },
    "w": 12,
    "x": 0,
    "y": 2.4
   },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MTBF",
     "metricsItem": { "label": "MTBF", "value": "MTBF" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "Top 10 Abnormal Reason",
   "type": "grouped-bar-chart-panel",
   "gridPos": {
    "h": 6.8,
    "i18n": { "en-US": { "h": 6.8, "w": 12, "x": 12, "y": 2.4 } },
    "w": 12,
    "x": 12,
    "y": 2.4
   },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "LastMonthAbReasonRank",
     "metricsItem": { "label": "LastMonthAbReasonRank", "value": "LastMonthAbReasonRank" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "MTTD",
   "type": "grouped-bar-chart-panel",
   "gridPos": {
    "h": 6.8,
    "i18n": { "en-US": { "h": 6.8, "w": 12, "x": 0, "y": 9.2 } },
    "w": 12,
    "x": 0,
    "y": 9.2
   },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MTTD",
     "metricsItem": { "label": "MTTD", "value": "MTTD" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "MTTR",
   "type": "grouped-bar-chart-panel",
   "gridPos": {
    "h": 6.8,
    "i18n": { "en-US": { "h": 6.8, "w": 12, "x": 12, "y": 9.2 } },
    "w": 12,
    "x": 12,
    "y": 9.2
   },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MTTR",
     "metricsItem": { "label": "MTTR", "value": "MTTR" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  }
 ]
}