{
 "title": "Monitoring Center",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "groupId", "label": "groupId", "query": "${VAR_GROUPID}" },
   { "name": "mapURL", "label": "mapURL", "query": "${VAR_MAPURL}" },
   { "name": "groupName", "label": "groupName", "query": "${VAR_GROUPNAME}" }
  ]
 },
 "panels": [
  {
   "title": "-",
   "type": "ifps-andon-switch-panel",
   "gridPos": {
    "h": 2.4,
    "i18n": { "en-US": { "h": 2.4, "w": 24, "x": 0, "y": 0 } },
    "w": 24,
    "x": 0,
    "y": 0
   }
  },
  {
   "title": "Event Status",
   "type": "advantech-indicator-panel",
   "gridPos": {
    "h": 4,
    "i18n": { "en-US": { "h": 4, "w": 8, "x": 0, "y": 2.4 }, "zh-TW": { "h": 4, "w": 8, "x": 8, "y": 0 } },
    "w": 8,
    "x": 0,
    "y": 2.4
   },
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel1",
     "metricsItem": { "label": "MC-Panel1", "value": "MC-Panel1" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "New Event",
   "type": "advantech-indicator-panel",
   "gridPos": {
    "h": 4,
    "i18n": { "en-US": { "h": 4, "w": 8, "x": 8, "y": 2.4 }, "zh-TW": { "h": 4, "w": 8, "x": 16, "y": 4 } },
    "w": 8,
    "x": 8,
    "y": 2.4
   },
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel3Singlestat",
     "metricsItem": { "label": "MC-Panel3Singlestat", "value": "MC-Panel3Singlestat" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    },
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel3Table",
     "metricsItem": { "label": "MC-Panel3Table", "value": "MC-Panel3Table" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "Principal Overview",
   "type": "advantech-indicator-panel",
   "gridPos": {
    "h": 4,
    "i18n": { "en-US": { "h": 4, "w": 8, "x": 16, "y": 2.4 }, "zh-TW": { "h": 4, "w": 8, "x": 16, "y": 0 } },
    "w": 8,
    "x": 16,
    "y": 2.4
   },
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel5Singlestat",
     "metricsItem": { "label": "MC-Panel5Singlestat", "value": "MC-Panel5Singlestat" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    },
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel5Table",
     "metricsItem": { "label": "MC-Panel5Table", "value": "MC-Panel5Table" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "Real-time Event",
   "type": "advantech-indicator-panel",
   "gridPos": {
    "h": 4,
    "i18n": { "en-US": { "h": 4, "w": 8, "x": 0, "y": 6.4 }, "zh-TW": { "h": 4, "w": 8, "x": 0, "y": 0 } },
    "w": 8,
    "x": 0,
    "y": 6.4
   },
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel2Singlestat",
     "metricsItem": { "label": "MC-Panel2Singlestat", "value": "MC-Panel2Singlestat" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    },
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel2Table",
     "metricsItem": { "label": "MC-Panel2Table", "value": "MC-Panel2Table" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "Overdue Event",
   "type": "advantech-indicator-panel",
   "gridPos": {
    "h": 4,
    "i18n": { "en-US": { "h": 4, "w": 8, "x": 8, "y": 6.4 }, "zh-TW": { "h": 4, "w": 8, "x": 16, "y": 4 } },
    "w": 8,
    "x": 8,
    "y": 6.4
   },
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel4Singlestat",
     "metricsItem": { "label": "MC-Panel4Singlestat", "value": "MC-Panel4Singlestat" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    },
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel4Table",
     "metricsItem": { "label": "MC-Panel4Table", "value": "MC-Panel4Table" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "Today Event",
   "type": "advantech-indicator-panel",
   "gridPos": {
    "h": 4,
    "i18n": { "en-US": { "h": 4, "w": 8, "x": 16, "y": 6.4 }, "zh-TW": { "h": 4, "w": 8, "x": 16, "y": 0 } },
    "w": 8,
    "x": 16,
    "y": 6.4
   },
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel6Singlestat",
     "metricsItem": { "label": "MC-Panel6Singlestat", "value": "MC-Panel6Singlestat" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    },
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel6Table",
     "metricsItem": { "label": "MC-Panel6Table", "value": "MC-Panel6Table" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "Factory Map",
   "type": "text",
   "gridPos": {
    "h": 7,
    "i18n": { "en-US": { "h": 7, "w": 16, "x": 0, "y": 10.4 } },
    "w": 16,
    "x": 0,
    "y": 10.4
   },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n",
   "targets": [
    {
     "groupID": "R3JvdXA.X-0tJMYGAgAG-fkZ",
     "groupName": "III",
     "groupNameItem": { "label": "III", "value": "R3JvdXA.X-0tJMYGAgAG-fkZ" },
     "metrics": "FlowCharting-Machines",
     "metricsItem": { "label": "FlowCharting-Machines", "value": "FlowCharting-Machines" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "Today Rank",
   "type": "advantech-datatable-panel",
   "gridPos": {
    "h": 7,
    "i18n": { "en-US": { "h": 7, "w": 8, "x": 16, "y": 10.4 }, "zh-TW": { "h": 9, "w": 4, "x": 16, "y": 8 } },
    "w": 8,
    "x": 16,
    "y": 10.4
   },
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel8",
     "metricsItem": { "label": "MC-Panel8", "value": "MC-Panel8" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  },
  {
   "title": "Events",
   "type": "advantech-datatable-panel",
   "gridPos": {
    "h": 10,
    "i18n": { "en-US": { "h": 10, "w": 24, "x": 0, "y": 17.4 }, "zh-TW": { "h": 10, "w": 24, "x": 0, "y": 21 } },
    "w": 24,
    "x": 0,
    "y": 17.4
   },
   "targets": [
    {
     "groupID": "$groupId",
     "groupName": "$groupId",
     "groupNameItem": {
      "__isNew__": true,
      "label": "$groupId",
      "value": "$groupId"
     },
     "metrics": "MC-Panel9",
     "metricsItem": { "label": "MC-Panel9", "value": "MC-Panel9" },
     "type": "table",
     "typeItem": { "label": "Table", "value": "table" }
    }
   ]
  }
 ]
}